services:
  - type: web
    name: seu-planner-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: VITE_API_URL
        value: https://seu-planner-api.onrender.com/api
        # value: http://localhost:5000/api  # Para desenvolvimento local
